version: '3.8'

services:
  photolog-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photolog-backend-prod
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    volumes:
      - ~/.oci:/root/.oci:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    name: photolog-prod-network
    driver: bridge